### ISSUE TITLE
Invalid argument supplied for foreach() 

### ISSUE THREAD

**Issue by alexschnapper** [bleeptrack/luftdaten-wordpress-plugin#4]
Wollte Widget in den Wordpress-Beitrag einbauen 

_Widgets can be used with shortcodes, too! Examples: [feinstaublive title=“Titel“ sensorIDs=“260,262″] [feinstaubampel title=“Titel“ sensorIDs=“260″]_

und folgendes gemacht:

[feinstaublive title=“Ostend, Mainufer, Westend Nord, Gutleutviertel, Europaviertel, Rödelheim und Nied“ sensorIDs=“1262,3111,2856,3241,3177,2818, 3423″]

dabei wurde in der Vorschau bei Wordpress folgender Fehler angezeigt:

`Warning: Invalid argument supplied for foreach() in /homepages/14/d13457383/htdocs/wp-content/plugins/live-widget-luftdaten/live-widget-luftdaten.php on line 424

Warning: Invalid argument supplied for foreach() in /homepages/14/d13457383/htdocs/wp-content/plugins/live-widget-luftdaten/live-widget-luftdaten.php on line 424

Warning: Invalid argument supplied for foreach() in /homepages/14/d13457383/htdocs/wp-content/plugins/live-widget-luftdaten/live-widget-luftdaten.php on line 424`

![screenshot from 2017-06-22 16-27-46](https://user-images.githubusercontent.com/1958292/27470542-c64addf4-57f4-11e7-97e4-4f4c1b3b77ae.png)

**Comment by bleeptrack** [comment]
Hi, ich habe gerade den gleichen Shortcode bei mir eingefügt und bekomme keine Fehler. Ich bin mir gerade auch nicht ganz sicher woran es liegt. Ich habe aber eine Vermutung: kannst du die Gänsefüßchen " bei dir nochmal löschen und selber tippen? Ich glaube, wenn man aus der Github Readme herauskopiert, dann nimmt er die falschen.

**Comment by alexschnapper** [comment]
Sorry, lange nicht mehr github gecheckt.. Hab jetzt jedenfalls das erneut eingegeben und auf eine Seite veröffentlicht, da kannst Du das auch sehen: https://alexander-schnapper.de/feinstaub/

**Comment by alexschnapper** [comment]
Kein Fehler mehr, hatte das mit den " falsch gesetzt. ticket geschlossen.
