### ISSUE TITLE
HTTPS not working

### ISSUE THREAD

**Issue by nekromoff** [bleeptrack/luftdaten-wordpress-plugin#5]
Iframes are pulling HTTP data and therefore they will get fully blocked (maps etc.)

![obrazok](https://user-images.githubusercontent.com/8550349/45962283-cddb7c00-c020-11e8-9bbe-710db7438e5b.png)

Please fix your map to be protocol independent using `//` instead of hardcoded `http://`

**Comment by bleeptrack** [comment]
fixed :)
